conditions:
  monday:
    0:
      conditions:
      - condition:
          video_id: null
          subscribed: true
          limit: 10
          
        query:
          # https://developers.google.com/youtube/v3/docs/search/list?hl=ja
          q: 
          videoCategoryId: 
          eventType: "live"
          videoEmbeddable: "true"
    1:
    2:
    3:
    4:
    5:
    6:
    7:
    8:
    9:
    10:
    11:
    12:
    13:
    14:
    15:
    16:
    17:
    18:
    19:
    20:
    21:
    22:
    23:
  tuesday:
  wednesday:
  thursday:
  friday:
  saturday:
  sunday:
