name: Update playlist

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check Out Repo 
      uses: actions/checkout@v3
    
    - name: Download token.json
      run: echo ${{ secrets.YOUTUBE_TOKEN_FILE }} | base64 -d > token.json

    - name: Install pipenv
      run: pipx install pipenv

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        cache: pipenv

    - name: Install dependencies
      run: pipenv install

    - name: Execute
      run: pipenv run main
      env:
        YOUTUBE_PLAYLIST_ID: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
        TZ: ${{ secrets.TZ }}

    - name: Upload tmp folder
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: token.json
        path: token.json
